templates:
  global:
    transmission:
      host: localhost
      port: 9091
      username: admin
      password: admin
#    quality: <720p
  tvfeeds:
    include:
      - tvfeeds.yml
#    verify_ssl_certificates: no
  tvseries:
    include:
      - series.yml
    download: yes
    remember_rejected: yes
    exists_series: /share/Multimedia/series/{{series_name}}/s{{series_season}}/
    set:
      path: /share/Multimedia/series/{{series_name}}/s{{series_season}}/
  tvanime:
    include:
      - anime.yml
    download: yes
    remember_rejected: yes
    exists_series: /share/Multimedia/anime/{{series_name}}/s{{series_season}}/
    set:
      path: /share/Multimedia/anime/{{series_name}}/s{{series_season}}/

tasks:
  tele task:
    template:
      - tvfeeds
      - tvseries
      - tvanime
    series:
      settings:
        lowres-series:
          quality: <720p
        hires-series:
          quality: 720p
          propers: 4 hours
        lowres-anime:
          quality: <720p
        hires-anime:
          quality: 720p
