templates:
  global:
    transmission:
      host: localhost
      port: 9091
      username: admin
      password: admin
  tvfeeds:
    include:
      - tvfeeds.yml
  animefeeds:
    include:
      - animefeeds.yml
  livefeeds:
    include:
      - livefeeds.yml
  tvanime:
    include:
      - anime.yml
    series:
      settings:
        lowres-anime:
          set:
            path: /share/Multimedia/anime/{{series_name}}/s{{series_season}}/
          quality: <720p
        hires-anime:
          set:
            path: /share/Multimedia/anime/{{series_name}}/s{{series_season}}/
          quality: 720p !10bit
    exists_series:
      - /share/Multimedia/anime/{{series_name}}/s{{series_season}}/
  tvseries:
    include:
      - series.yml
    series:
      settings:
        lowres-series:
          set:
            path: /share/Multimedia/series/{{series_name}}/s{{series_season}}/
          quality: <=720p
          target: <720p
          timeframe: 2 hours
        hires-series:
          set:
            path: /share/Multimedia/series/{{series_name}}/s{{series_season}}/
          quality: 720p
          propers: 4 hours
          timeframe: 4 hours
    exists_series:
      - /share/Multimedia/series/{{series_name}}/s{{series_season}}/
  tvsports:
    include:
      - sports.yml
 
tasks:
  tele task:
    template:
      - tvfeeds
      - tvseries
  anime task:
    template:
      - animefeeds
      - tvanime
  live task:
    template:
      - livefeeds
      - tvsports
