templates:
  global:
    transmission:
      host: localhost
      port: 9091
      username: admin
      password: admin
      path: /share/Multimedia/series/{{series_name}}/s{{series_season}}/
    remember_rejected: yes
    exists_series:
      - /share/Multimedia/anime/{{series_name}}/s{{series_season}}/
      - /share/Multimedia/series/{{series_name}}/s{{series_season}}/
  tvfeeds:
    include:
      - tvfeeds.yml
  livefeeds:
    include:
      - livefeeds.yml
  tvanime:
    include:
      - anime.yml
    series:
      settings:
        lowres-anime:
          set:
            path: /share/Multimedia/anime/{{series_name}}/s{{series_season}}/
          quality: <720p
        hires-anime:
          set:
            path: /share/Multimedia/anime/{{series_name}}/s{{series_season}}/
          quality: 720p !10bit
  tvseries:
    include:
      - series.yml
    series:
      settings:
        lowres-series:
          set:
            path: /share/Multimedia/series/{{series_name}}/s{{series_season}}/
          quality: <=720p
          target: <720p
          timeframe: 2 hours
        hires-series:
          set:
            path: /share/Multimedia/series/{{series_name}}/s{{series_season}}/
          quality: 720p
          propers: 4 hours
          timeframe: 4 hours
 
tasks:
  tele task:
    template:
      - tvfeeds
      - tvanime
      - tvseries
  live task:
    template:
      - livefeeds
    accept_all: yes
